name: Backend CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  deploy-main:

    runs-on: ubuntu-latest
    if: "(contains(github.event.head_commit.message, '[update]') || github.event_name == 'workflow_dispatch') && github.ref_name == 'main'"

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v3
      
      - name: Environment preparation
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          chmod -R go= ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY_MAIN }}" >> ~/.ssh/id_rsa

      - name: Deploy to Server
        run: |
          chmod 700 ci-scripts
          cd ci-scripts
          ansible-playbook -i "${{ secrets.REMOTE_HOST_MAIN }}" ${{ secrets.ANSIBLE_DEBUG_LEVEL }} -e "ansible_user=${{ vars.REMOTE_USER_MAIN }} ansible_port=${{ vars.REMOTE_PORT_MAIN }} \
          BACKEND_BIN=${{ vars.BACKEND_BIN }} \

          DB_ROOT_PASS=${{ secrets.DB_ROOT_PASS }} \
          DB_USER_PASS=${{ secrets.DB_USER_PASS }} \

          SRC_DIR=${{ github.workspace }}/" wordpress-update.yml;
    timeout-minutes: 15